config/routes.rb
Pyropus::Application.routes.draw do
  controller :congress do
    get "congress/query/*args" => :query
    get "congress/" => :index
  end

  resources :things
  match "pfxed" => "pfxed#show", via: :get
  match "pfxed" => "pfxed#create", via: :post
  resources :pfxed do
    collection do
      get "list"
    end
  end

  root to: 'posts#index'

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
    get "logout" => :destroy
  end

  resources :users

  resources :posts

  match "/:url" => 'posts#show'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]
  # GET /things
  # GET /things.json
  def index
    page_title "View all things"
    @things = Thing.all

    @things.each do |thing|
      # TODO: make this into a helper
      thing.description = thing.description[0..500]

      # stop at the end of the first paragraph
      thing.description = thing.description.split("\r\n\r\n")
      thing.description = thing.description[0]

      # remove the last word (fragment)
      thing.description = thing.description.split(" ")
      thing.description = thing.description[0..-1]
      thing.description = thing.description.join(" ")
      thing.description = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true).render(thing.description)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])
    @thing.description = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true).render(@thing.description)
    page_title "About the " + @thing.name + " thing"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<% @things.each do |thing| %>
  <div class="thing">
    <h1 class="title"><%= thing.name %></h1>
    <p><%= raw thing.description %></p>
    <span class="actions">
        <%= ajax_link_to "View Thing", controller: thing.path %>
        <%= ajax_link_to 'Read More', thing %>
        <% if admin? %>
          <%= ajax_link_to 'Edit', edit_thing_path(thing) %>
          <%= ajax_link_to 'Destroy', thing, confirm: 'Are you sure?', method: :delete %>
      <% end %>
    </span>
  </div>
<% end %>

<span class="actions">
  <% if admin? %>
    <%= ajax_link_to 'New Thing', new_thing_path %>
  <% end %>
</span>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<div class="thing">
<%= raw @thing.description %>

<span class="actions">
  <% if admin? %>
    <%= link_to 'Edit', edit_thing_path(@thing) %>
  <% end %>
  <%= link_to 'View Thing', :controller => @thing.path %>
  <%= link_to 'Back', things_path %>
</span>
</div>