config/routes.rb
Pyropus::Application.routes.draw do
  controller :congress do
    get "congress/query/*args" => :query
    get "congress/" => :index
  end

  resources :things
  match "pfxed" => "pfxed#show", via: :get
  match "pfxed" => "pfxed#create", via: :post
  resources :pfxed do
    collection do
      get "list"
    end
  end

  root to: 'posts#index'

  controller :session do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
    get "logout" => :destroy
  end

  resources :users

  resources :posts

  match "/:url" => 'posts#show'

end

app/views/shared/_footer.html.erb
<div id="footer">
</div>

app/views/shared/_header.html.erb
<div id="header-wrap">
  <div id="header">
    <div id="titlebar">
      <h1 id="site_title">Pyrop.us</h1>
    </div>
    <div id="menubar">
      <%= render partial: 'shared/menubar' %>
      <div class="clearfix">&nbsp;</div>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<div id="navlogin">
<% if logged_in %>
  <div id="username">Logged in as <%= username %></div><div id="logout"><%= link_to "X", logout_url, remote: true %></div>
  <div class="clearfix"></div>
<% else %>
  <%= form_tag login_url, remote: true do %>
    <%= submit_tag "Login", id: "login-button", class: "initial" %>
    <%= text_field_tag :name, params[:name], placeholder: "Username", id: "username-text" %>
    <%= password_field_tag :password, params[:password], placeholder: "Password", id: "password-text" %>
    <%= hidden_field_tag :redirect_on_login, request.url %>
  <% end %>
<% end %>
</div>

app/views/shared/_menubar.html.erb
<div id="menu">
<%= render partial: 'shared/login' %>
<%= render partial: 'shared/navlinks' %>
</div>

app/views/shared/_navlinks.html.erb
<ul id="navlinks">
<li><%= ajax_link_to "Posts", posts_url %></li>
<li><%= ajax_link_to "Things", things_url %></li>
<% if admin? %>
<li><%= ajax_link_to "Users", users_url %></li>
<% end %>
<% cache ('cms_menu_items') do |i| %>
  <% Post.where('url IS NOT NULL AND url != ""').each do |i| %>
    <li><%= ajax_link_to i.title, "/#{i.url}" %></li>
  <% end %>
<% end %>
<div class="clearfix"></div>
</ul>